view park
CNDvn/ParkingApp-Mobile pull request #10
Opened 2022-01-29 13:55 UTC by NguyennKhoaa

view park cua em

2022-01-29 14:16 UTC, DQLok commented on lib/configs/routes/routes.dart
> +}
rebase this file OK!!!!

2022-01-29 14:16 UTC, DQLok commented on lib/main.dart
>    }
rebase this file OK!!!!

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +        iconTheme: const IconThemeData(color: Color(0xff3277DB)),
you should create color in AppColor and use it

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +            constraints: const BoxConstraints.expand(height: 280),
use => Size size = MediaQuery.of(context).size;  for Height and Width

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                  height: 40,
use => Size size = MediaQuery.of(context).size;  for Height and Width

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                Image.asset("assets/images/xe.png"),
all widget use SizeBox(child: /*your widget*/)

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                        style: TextStyle(color: Color(0xff606470), fontSize: 16))
you should create color in AppColor and use it

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                    style: TextStyle(color: Color(0xff606470), fontSize: 25, fontWeight: FontWeight.bold),
you should create color in AppColor and use it

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                  style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: Color(0xff333333)),
you should create color in AppColor and use AppTextStyle

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                        style: TextStyle(color: Color(0xff606470), fontSize: 16))
use AppTextStyle

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                            const SizedBox(width: 10,),
use => Size size = MediaQuery.of(context).size; for Height and Width

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                            const SizedBox(width: 45,),
use => Size size = MediaQuery.of(context).size; for Height and Width

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                            const SizedBox(width: 45,),
use => Size size = MediaQuery.of(context).size; for Height and Width

2022-01-29 14:16 UTC, DQLok commented on lib/view/viewPark/view_park.dart
> +                      const SizedBox(height: 130),
use => Size size = MediaQuery.of(context).size; for Height and Width

2022-01-29 14:40 UTC, baosphoa0403 requested changes
Please tell me about it

2022-01-29 14:40 UTC, baosphoa0403 commented on lib/view/viewPark/view_park.dart
> +class ViewPark extends StatefulWidget {
Can you explain for me why Stateful ?

2022-01-29 14:40 UTC, baosphoa0403 commented on lib/widgets/button/button_view_park.dart
> +class ButtonViewPark extends StatelessWidget {
Please explain why don't use ButtonBase

2022-01-30 05:36 UTC, DQLok approved these changes

2022-01-30 06:24 UTC, baosphoa0403 approved these changes
review done

2022-01-31 04:00 UTC, merged