lok/PAM-10
CNDvn/ParkingApp-Mobile pull request #11
Opened 2022-01-30 05:56 UTC by DQLok

Google and local

2022-01-30 14:07 UTC, baosphoa0403 requested changes

2022-01-30 14:07 UTC, baosphoa0403 commented on lib/widgets/Drawer/drawer.dart
> +                  //backgroundImage:
please remove comment

2022-01-30 14:07 UTC, baosphoa0403 commented on lib/view/google_map/google_map.dart
> +    // String _address = "";
please remove comment

2022-01-31 12:10 UTC, baosphoa0403 approved these changes

2022-01-31 12:24 UTC, lpduy2k approved these changes

2022-01-31 12:25 UTC, merged